export const popularSearches = [
    {
      id: 1,
      title: "Smartphones",
      category: "Electronics",
      image: "",
      price: 0,
      description: "",
      stock: 0,
      rating: 0,
      brand: "Brand A",
      model: "Model X",
      color: "Black",
      discount: 0,
    },
    {
      id: 2,
      title: "Laptops",
      category: "Electronics",
      image: "",
      price: 0,
      description: "",
      stock: 0,
      rating: 0,
      brand: "Brand B",
      model: "Model Y",
      color: "Silver",
      discount: 0,
    },
    {
      id: 3,
      title: "Headphones",
      category: "Accessories",
      image: "",
      price: 0,
      description: "",
      stock: 0,
      rating: 0,
      brand: "Brand C",
      model: "Model Z",
      color: "White",
      discount: 0,
    },
    {
      id: 4,
      title: "Books",
      category: "Literature",
      image: "",
      price: 0,
      description: "",
      stock: 0,
      rating: 0,
      brand: "Brand D",
      model: "Model W",
      color: "Blue",
      discount: 0,
    },
  ];